import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 8,
      paddingTop: 4,
    },
    card: {
      width: '95%',
      maxWidth: 400,
      // elevation: 4,
      alignItems: 'stretch',
      backgroundColor: '#fff',
      // borderRadius: 18,
      padding: 24,
    },
    title: {
      textAlign: 'center',
      marginBottom: 4,
      color: '#222',
    },
    subtitle: {
      textAlign: 'center',
      marginBottom: 24,
      color: '#444',
      fontSize: 16,
      fontWeight: '400',
    },
    label: {
      marginTop: 12,
      marginBottom: 4,
      color: '#222',
      fontSize: 14,
      fontWeight: '500',
    },
    input: {
      height: 44,
      borderWidth: 1,
      borderColor: '#E0E0E0',
      borderRadius: 8,
      paddingHorizontal: 12,
      backgroundColor: '#F8F8F8',
      fontSize: 16,
      marginBottom: 4,
      color: '#222',
    },
    signInButton: {
      backgroundColor: '#181B23',
      borderRadius: 8,
      height: 48,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 16,
      marginBottom: 8,
    },
    signInButtonText: {
      color: '#fff',
      fontSize: 18,
      fontWeight: 'bold',
      letterSpacing: 1,
    },
    signUpRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      margin: 24,
      paddingBottom: 50,
    },
    signUpText: {
      fontSize: 15,
    },
    signUpLink: {
      color: '#0a7ea4',
      fontWeight: 'bold',
      fontSize: 15,
      marginLeft: 2,
      textAlign: 'center',
    },
  }); 